project:
  type: website

website:
  title: "Westman Naturalists"
  navbar:
    left:
      - text: "Events"
        href: events.qmd
      - text: "Membership"
        href: membership.qmd
      - text: "Helping out"
        href: helping_out.qmd
      - text: "Articles"
        href: articles.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Videos"
        href: videos.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: facebook
        href: https://www.facebook.com/westman.naturalists/
      - icon: instagram
        href: https://www.instagram.com/westmannaturalists/

format:
  html:
    theme:
     - simplex
     - styles.scss
    page-layout: full
    grid:
      body-width: 700px
      margin-width: 250px


execute:
  echo: false
  message: false
  warning: false
