---
title: "Bylaws"
---

Westman Naturalists Inc.  
By-laws approved by Board, April 28, 2025

## 1. DEFINITIONS

The following definitions shall apply to all By-laws.  
“Act” means The Corporations Act, CCSM c C225, as amended from time to time.  
“Board” means the Board of Directors of the Westman Naturalists Inc.   
“By-laws” means these and any other by-laws of the Westman Naturalists.  
“Club” means Westman Naturalists Inc.  
“Meeting” means annual General Meetings, special General Meetings, or Board of Directors’ meetings.  
“Members” means persons who hold current membership in the Westman Naturalists Inc.  

## 2. OBJECTIVES

2.1 The objectives of the Club are as follows:  

- To offer nature-related educational opportunities and knowledge sharing activities such as presentations, field trips, and publications.
- To encourage study and protection of the natural world.
- To assist in the collection and provision of data related to species and the natural environment for statistical and educational purposes.
- To act as stewards of the environment.

## 3. CLUB MEMBERSHIP
3.1 Membership shall be open to all persons interested in nature and the environment, and who support the objectives of the Club.

3.2 Membership is not required to participate in outings, presentations, or to receive the Club’s newsletters.

3.3 Members who pay dues are eligible to vote and have direct input into the programs and activities of the Club. 

3.4 	Memberships are not transferable, nor are dues refundable.

3.5	Notice of a proposed change in fees must be given by the Board of Directors at least a month in advance. Any change in the annual fees for Members shall be determined by a two-thirds majority vote of Members in attendance at a General Meeting. Any changes shall take effect in the following calendar year.

3.6	There shall be three classes of membership. Any Member can be part of a committee. 

3.6.1 	Individual – Persons eighteen years or older who pay annual dues are eligible to vote, serve on a committee, and hold office.

3.6.2 	Youth – All youth under the age of eighteen years need parental or guardian consent to obtain membership or join a committee. Youth sixteen years of age or older may obtain individual membership, pay annual fees, serve on a committee and can vote at a General Meeting. Youth younger than sixteen years can serve on a committee without being a paying Member and are not entitled to vote. 

3.6.3 	Honorary Life – Persons may be named honorary life Members by the Board in recognition of outstanding service or significant in-kind or financial contributions to the Club. They are not required to pay membership dues and are entitled to vote and hold office.

3.7 	The Members list and other contact information are considered confidential and shall not be sold or otherwise provided to a third party. Where required, as per Section 21 of the Act, Members will be notified in advance.

3.8 	A Member in good standing may be approved by the Board to speak or act on behalf of the Club in specific circumstances. 

## 4. BOARD OF DIRECTORS

4.1	The affairs of the Club shall be managed by a Board of Directors, up to a maximum of eleven Directors. Election of new Directors by the general membership occurs at the annual General Meeting. Directors must be eighteen years of age or older, and be, and remain during their term, a Member of the Club. Each newly elected Director is expected to serve a three-year term and can be renewed by a vote at the annual General Meeting. 

4.2 	The first meeting of a new Board of Directors shall take place at the call of the retiring or current President, and regular meetings shall be held at the pleasure of the Board. Retiring Directors are invited to attend the first meeting of the new Board to facilitate the orderly transfer of responsibilities.

4.3 	The Board of Directors consist of the positions of Past President, President, Vice- President, Secretary, Treasurer, and up to six Directors at Large. They are the “officers” and are responsible for day-to-day operations. Each Westman Naturalists committee shall have at least one Director as a committee member. Each committee shall appoint a chairperson amongst its members. A committee chair does not need to be a Director.

4.4	The President shall:   

- Preside at any meetings of the Board. In the President’s absence, the Vice-president shall chair the meeting and in the absence of both, a chair may be selected from Directors at the meeting to preside. 
- Be an ex-officio member to all committees, in an advisory role. 
- Serve on a committee; however, if serving on only one committee, it should not be the same committee as the Vice-president. 
- Present a year-end report at the annual General Meeting.
- Carry out the duties of the Immediate Past President in the event of the Past President’s absence. 

4.5	The Vice-President shall:   

- Carry out the duties of the President in the event of the President's absence and any other duties as may be assigned from time to time by the Board. 
- Serve on a committee; however, if serving on only one committee, it should not be the same committee as the President.
    
4.6 	The Secretary shall:   

- Have charge of the minutes of Board meetings, and general meetings including the annual General Meeting, and be under the direction of the President and the Board. In the absence of the Secretary at any meeting, their duties shall be discharged by a designate appointed by the meeting chair. 

4.7	The Treasurer shall:   

- Receive all money paid to the Club and shall be responsible for the deposits in whatever financial institution the Board may order. 
- Maintain a full account of receipts and disbursements and present interim financial statements to the Board whenever requested. 
- Collect and track the annual membership fees and make the list available to the Board of Directors.
- Prepare a financial statement for the annual General Meeting and submit a copy of the same to the Secretary. 
4.8 	The Immediate Past President shall:   

- Be the previous elected President of the Club. If this person is unavailable, the Board may select one of the other past Presidents, or a person appointed by the Board. 
- Assist in recruiting nominations for new Board members and offer an orientation to new Board members.
- Conduct the annual election of Directors at the annual General Meeting.
- Offer advice based on previous experience in presiding over the Club. 

4.9	A Director at Large shall:   

- Promote the Club to the public, participate on committees and perform selected duties as assigned from time to time by the Board.  

4.10 	Officers are authorized to sign official documents of the Club. Two signatures from four people appointed by the Board, shall have signing authority. Other Members may be afforded signing authority by the Board, for specific purposes and periods of time.

4.11 	A Director may resign from the Board by written notice. The Board may name a successor until the next annual General Meeting. A Director ceases to hold office when that Director is declared to be bankrupt or is removed from office by a majority vote of Members at a meeting called for that purpose.

4.12 	A Director who is absent from three successive Board meetings without providing reasonable cause may be considered as having resigned from the Board.

4.13 	All Directors should be familiar with the conflict-of-interest policy. Any Director who believes they may have a real or perceived conflict of interest – financially or morally – with a matter that has come before the Board, shall immediately identify to the Board such believed conflict, and refrain from entering discussion or vote on such matter. The Secretary shall record in the Minutes the declared conflict. 

4.14	Every Director shall:  
a) Act honestly and in good faith with a view to the best interests of the Club; and  
b) Exercise the care, diligence and skill that a reasonably prudent person would exercise in comparable circumstances.

4.15	Every Director shall comply with the Act and its regulations, the articles of incorporation and the Club’s by-laws.

4.16 	Directors shall serve without remuneration, except that the Board may approve payment of out-of-pocket expenses to Directors for assigned duties when valid receipts are presented.

## 5. MEETINGS OF MEMBERS

5.1	The annual General Meeting of the Members of the Club shall be held annually in Westman, in the second quarter (April, May, June). Members shall be notified of the Meeting and agenda sent in an email at least 14 days in advance. Minutes will be distributed to the Members within one month and again with the agenda for the next annual General Meeting. 

5.2 	Annual General Meetings will normally be in-person, with no option to participate and vote by electronic means. If deemed necessary, the Board may authorize a hybrid or an exclusively “remote” meeting via electronic means. In this case, Members may participate by phone or electronic means that permit all participants to communicate adequately with each other during the meeting. Members participating by such means are deemed to be present at that meeting. 

5.3 	Annual reports of committees shall be received at the annual General Meeting. Any new Directors of the Board or renewal of a Director to another term will be appointed through a majority vote of the Members present at the annual General Meeting. The Officers of the Club shall be presented to the members attending the annual General Meeting. 

5.4 	Special General Meetings may be called by any two Directors, with the approval of the Board, provided two weeks’ notice is given to all Members. The reason for the meeting must be provided to the Members.

5.5 	The President, or in their absence the Vice-President, shall chair Special General Meetings. The Secretary, or an acting secretary, shall record the proceedings of such Meetings and shall distribute minutes to members within one month.

5.6 	Field Trips conducted by the authority of the Club shall be led by at least one Director and by one or more committee-approved persons. At all times safety shall be of uppermost importance. Participants need not be Club members. All participants shall sign a waiver that relieves the Club of personal liability. 

5.7	Presentations conducted by the authority of the Club shall be led by at least one Director and by one or more committee-approved persons. 

## 6. MEETINGS OF THE BOARD

6.1	Regular meetings of the Board shall be normally held every two months. Dates of the meetings may be adjusted based upon availability of Board members. 

6.2	With Board permission, a Director may participate in Board meetings by phone or electronic means that permit all participants to communicate adequately with each other during the meeting. A member participating by such means is deemed to be present at that meeting.

6.3	Notice of meeting and agenda shall be sent to Board members at least seven days prior to each meeting. 

6.4	Committee reports and updates shall be received at Board meetings, in addition to new business. 

6.5	Board meeting minutes shall be taken by the Secretary and shall be distributed with the next meeting agenda, or earlier, if possible.  

## 7. CONDUCT OF MEETINGS

7.1	All Meetings of the Club shall be conducted in accordance with “Roberts Rules of Order”.

7.2	Fifty percent of Directors shall form a quorum at a Board meeting, and ten percent of voting members of the Club shall form a quorum at a General Meeting.

7.3	Voting on resolutions shall normally be by show of hands of those Members present. A simple majority, except as required elsewhere in these By-laws, shall rule. Each Member shall have one vote. A tie vote shall be considered a defeated motion.

7.4 	The chair of a Meeting may request that a ‘motion’ or ‘resolution’ proposed by a Member be in writing and signed by the ‘mover’ and ‘seconder.’

7.5	All motions or resolutions shall be seconded before debate is allowed.

7.6	At Board meetings, a recorded vote may be requested by a Director. Any two Directors may request a secret ballot vote on a resolution. A Director may, upon request, be recorded as being against a resolution.

7.7	At Board meetings each Director personally present, or present via telephone conference or videoconference, shall be entitled to one vote.  

7.8	A resolution in writing signed by all Directors or confirmed by means of electronic mail (email) by all Directors, shall be as valid and effectual as if it had been passed at a Board meeting duly called and constituted.

## 8. CONDUCT OF BUSINESS

8.1	The Head Office of the Club shall be in the Westman area of Manitoba. Where a postal box address is unacceptable, the resident address of a designated Director may be listed.

8.2	The financial year of the Club shall be the calendar year.

8.3	Banking and financial transactions shall be conducted with institutions satisfactory to the Board.

8.4	All monies are payable only to the “Westman Naturalists Inc.”

8.5	Authority for the purchase, acquisition or transfer of any service or asset shall be vested in the Board.

8.6	The Club records shall be maintained in accordance with the Act.

8.7	The Board may order a financial audit undertaken by a qualified professional, when deemed necessary. 

## 9. INDEMNITY

9.1	Directors and Officers are indemnified in accordance with Section 119 of the 	Act.

## 10. COMMITTEES

10.1	The Board may establish, by resolution, “standing” (permanent) and “ad hoc” (temporary) committees for the purpose of achieving objectives. At least one member of any standing Committee shall be a Director. The President or a designate from among the Board shall be an ex-officio member, in an advisory capacity, of all Committees.

10.2	Standing committees shall hold formal meetings, issue regular reports, or provide other forms of communication, to the satisfaction of the Board. Each committee shall appoint a chairperson amongst its members. A committee chair does not need to be a Director.

## 11. COMMUNICATION

11.1	Where appropriate, the Board or a designate, may communicate verbally, or by news media, postal service, or email with Members, with other organizations, or with the general public.

11.2	The Club may operate a website and or social media sites or platforms for the purpose of disseminating information about the Club and any other matters deemed purposeful.

## 12. PUBLICATIONS

12.1	The Club may produce and dispense, or sell, material that is related to its objectives.

## 13. AFFILIATIONS

13.1	The Board may authorize membership in, or partnerships with, appropriate organizations that share the Club’s objectives. 

## 14. CLUB BY-LAWS

14.1	By-law changes or amendments shall be approved by the Board before being presented to the Members.

14.2	The Members shall be given at least one month’s advance notice of the proposed presentation of new or amended by-laws.

14.3	The proposed by-law changes or amendments must receive a two thirds majority of voters at a general membership meeting where such proposals have been presented.

14.4	New by-laws shall come into effect immediately after they are approved, except that changes to membership dues will not come into effect until January 01 of the year following approval.

14.5	In the event of an extreme circumstance that negates the conduct of the business of the Club; two Officers of the Board are empowered to temporarily authorize a person, in writing, to conduct a necessary activity until the Board or the Membership can satisfy that circumstance.

14.6	The Board shall have the authority to develop and maintain ‘policies’ and ‘procedures’ which provide specific direction regarding the interpretation of these by-laws.

## 15. DISSOLUTION

15.1 	Dissolution of the Club will be decided by a unanimous vote of the Board.

15.2	All debts of the Club must be paid in full before dissolution.

15.3	Where there are existing legal arrangements to do so the Club’s assets may be dispersed to charitable organizations on dissolution.

15.4	The Board may choose to disperse assets to charitable organizations not subject to legal agreements if such organizations have similar objectives to the Club. 


**Approved: April 28, 2025**
<!--Revised:-->
