---
title: "Christmas Bird Counts"
---

The Christmas Bird Count is a citizen science project that started in the year 1900. December 2024 marks the 125th Christmas Bird Count season, and Westman Naturalists once again hosted two counts. Results for the 2024 Brandon and Rivers counts can be found below.

Westman Naturalists has been organizing the Brandon Christmas Bird Count since 2019. There are two ways you can participate in the count, either as a field counter or as a feeder watcher. Field counters are placed in groups and are assigned an area around the city, such as the north hill or downtown, and then walk or drive around counting any birds they spot. Feeder watchers keep an eye out for birds visiting their feeders or backyard, marking down any unique birds or flocks. There is also always a chance of encountering something besides birds, such as two families of North American River Otters that were found along the river in 2023.

### 2025 Christmas Bird Counts

## Brandon CBC Results {#brandon25}

::::{.columns}
:::{.column width=60%}
The 2025 Brandon Christmas Bird Count took place on Sunday, December 14th. Results will be added when their completed, please check back later!

:::
:::{.column width=40%}
{{< video https://www.youtube.com/embed/d5oRWSEt71Y >}}
::::

## Rivers CBC Results {#rivers25}

::::{.columns}
:::{.column width=60%}
The 2025 Rivers Christmas Bird Count took place on Sunday, December 28th. Results will be added when their completed, please check back later!

:::
:::{.column width=40%}
{{< video https://www.youtube.com/embed/A4sZGq8ghtE >}}
::::

### 2024 Christmas Bird Counts

## Brandon CBC Results {#brandon24}

::::{.columns}
:::{.column width=60%}
The 2024 Brandon Christmas Bird Count took place on Sunday, December 15th. This year we had 35 field counters and 24 feeder watchers in the 1 count circle. 39 different species were counted for a grand total of 4869 birds.

We hosted a potluck supper for participants after everyone was done counting for the day. 16 members shared stories of what they saw during the count, such as a flock of Cedar Waxwings eating berries, a lone Common Merganser on the river, and White-winged Crossbills showing up right as they were being discussed.

:::
:::{.column width=40%}
{{< video https://www.youtube.com/embed/yFgX_L4y518 >}}
::::

| Species | Count |
|---------|------:|
| Common Merganser | 1 |
| Grey Partridge | 316 |
| Ruffed Grouse | 1 |
| Sharp-tailed Grouse | 141 |
| Wild Turkey | 35 |
| Bald Eagle | 3 |
| Sharp-shinned Hawk | 3 |
| Cooper's Hawk | 1 |
| Rock Pigeon | 1863 |
| Eurasian Collared Dove | 12 |
| Mourning Dove | 1 |
| Great Horned Owl | 1 |
| Snowy Owl | 2 |
| Downy Woodpecker | 48 |
| Hairy Woodpecker | 32 |
| Northern Flicker | 3 |
| Pileated Woodpecker | 2 |
| Merlin | 4 |
| Northern Shrike | 2 |
| Blue Jay | 78 |
| Black-billed Magpie | 63 |
| American Crow | 67 |
| Common Raven | 76 |
| Black-capped Chickadee | 378 |
| Red-breasted Nuthatch | 28 |
| White-breasted Nuthatch | 105 |
| Brown Creeper | 3 |
| American Robin | 35 |
| European Starling | 45 |
| Cedar Waxwing | 30 |
| Snow Bunting | 148 |
| Dark-eyed Junco | 35 |
| Red-winged Blackbird | 1 |
| Purple Finch | 1 |
| House Finch | 140 |
| Red Crossbill | 4 |
| White-winged Crossbill | 40 |
| Pine Siskin | 9 |
| House Sparrow | 1111 |

## Rivers CBC Results {#rivers24}

::::{.columns}
:::{.column width=60%}
The 2024 Rivers Christmas Bird Count took place on Sunday, December 29th. We had a record number of 31 field counters spread out over eight sectors of the count circle, and 9 feeder watchers around the Rivers area. 32 different species were counted for a grand total of 1251 birds.

A lot of owls were spotted this year, with 8 individuals representing 4 species! It seems to be an irruption year for Great Greys. There were many large black birds, American Crows and Common Ravens, and even a few small blackbirds, a Common Grackle and two Rusty Blackbirds.

:::
:::{.column width=40%}
{{< video https://www.youtube.com/embed/ZD8ZGBVdao4 >}}
::::

| Species | Count |
|---------|------:|
| Mallard | 1 |
| Grey Partridge | 66 |
| Sharp-tailed Grouse | 89 |
| Wild Turkey | 15 |
| Bald Eagle | 7 |
| Rock Pigeon | 159 |
| Eurasian Collared Dove | 20 |
| Mourning Dove | 4 |
| Great Grey Owl | 4 |
| Great Horned Owl | 2 |
| Snowy Owl | 1 |
| Northern Saw-whet Owl | 1 |
| Downy Woodpecker | 23 |
| Hairy Woodpecker | 16 |
| Pileated Woodpecker | 3 |
| Merlin | 2 |
| Northern Shrike | 5 |
| Blue Jay | 43 |
| Black-billed Magpie | 66 |
| American Crow | 78 |
| Common Raven | 148 |
| Black-capped Chickadee | 136 |
| Red-breasted Nuthatch | 1 |
| White-breasted Nuthatch | 32 |
| Brown Creeper | 1 |
| Snow Bunting | 200 |
| Dark-eyed Junco | 6 |
| Rusty Blackbird | 2 |
| Common Grackle | 1 |
| Pine Grosbeak | 3 |
| House Finch | 6 |
| House Sparrow | 110 |

## Other Counts Around Westman {#othercounts}

The Glenboro/Spruce Woods count took place on December 14th. Results were posted in the January 9th copy of The Gazette.

The Riding Mountain National Park count took place on December 17th.

The Minnedosa count took place on December 28th. Results were shared with the Minnedosa Tribune.

Results for counts across Canada will be available from [Birds Canada](https://www.birdscanada.org/bird-science/christmas-bird-count) when they are completed.

<!--
## Christmas Bird Count

- [Car Sign](resources/CBCVehicleSign_EN.pdf)  
  A sign to print out and keep in/on your car to let others know what we're up to.
  
- [Participants Guide](resources/Participants_Guide_to_CBC_Cheat_Sheet.01.pdf)  
  Details about the CBC

- [Top 3 ways to support Christmas Bird Count](resources/Top3WaysToSupportCBC_EN.pdf)  
  How to support the CBC

- [Christmas Bird Count Safety](resources/Xmas Count Safety.pdf)  
  How to be safe during the CBC
-->
