---
title: "Helping out"
---

Are you interested in Helping Out or supporting Nature? 
Here we have listed a number of links to projects that are looking for help in 
protecting or researching nature, from birds to bats and habitats.

See what appeals to you! 

## Westman Naturalists Presentations

These projects are ones which have given talks to us or taken us out on excursions, 
and which are all looking for volunteers to help out in various ways.

Some are **local**, requiring you to go outside, count birds, set up boxes, etc.
Others are **online**, in which you can participate from the comfort of your own 
home. 

- [Manitoba’s Important Bird Area Program](https://importantbirdareasmb.ca/volunteer) [**Local**]
  - We've had several presentations and events with the IBA over the years and
  they are always looking for volunteers to help out from participating in a "Blitz" to those who care for specific IBAs.

- [Zooniverse Woodpecker Cavity Cam](https://www.zooniverse.org/projects/elwest/woodpecker-cavity-cam) [**Online**]
  - In October 2021, [Dr. Elena West](https://www.rhworesearch.org/) shared a presentation on her work with red-headed woodpeckers and the citizen science project they've set up through the Zooniverse to help identify what's going on in their trail camera pictures. 

- [Canada-wide Batbox project](https://wcsbats.ca/Our-work-to-save-bats/Batbox-Project/BatBox-Project-Canada-wide) [**Local**]
  - In March 2021, Karen Vanderwolf talked to us about the Batbox project and white-nose syndrome. Check out the project if you're interested in joining this study.

- [Manitoba Burrowing Owl Recovery Programs](https://mborp.ca/) [**Local**]
  - In September 2020, Alexandra Froese talked to us about the 
  Manitoba Burrowing Owl Recovery Programs. 
  - To help out, you can report Burrowing Owl sightings
  or volunteer your time to help dig burrows, put up release pens or to help with 
  surveys. 

- [Assiniboine Food Forest](https://www.assiniboinefoodforest.com) [**Local**]
  - In August 2019 Dave Barnes took us for a walk around the Assiniboine Food Forest. 
  - You can volunteer to help out with various tasks.

## Annual events

These annual citizen science events are always worth supporting with your time
and energy! Currently the list is for birding events, but we hope to add other,
non-bird related events too!

- [Christmas Bird Count](https://www.birdscanada.org/bird-science/christmas-bird-count/) [**Local; Dec-Jan**]
- [Project Feeder Watch](https://feederwatch.org/) [**Local; Nov-Apr**]
- [Great Backyard Bird Count](https://www.birdcount.org/) [**Local; Feb**]
- [Global Big Day](https://ebird.org/globalbigday) [**Local; May**]

## Other Nature-related organizations

- [Bee City Brandon](https://www.beecitybrandon.com/)
- [Friends of the Bluebirds](http://www.mbbluebirds.org/)
- [Manitoba’s Important Bird Area Program](https://importantbirdareasmb.ca/)
- [Nature Manitoba](http://www.naturemanitoba.ca/)
- [Manitoba Chimney Swift Initiative](http://www.mbchimneyswift.com/)
- [Manitoba Breeding Bird Atlas](https://www.birdatlas.mb.ca)

