---
title: "Resources"
toc: true
---

## Waiver
- View a digital copy of our standard [outings waiver](resources/WNwaiver202405.pdf). A physical copy will be present at most of our outings for participants to sign.

## Checklists

- [Westman Naturalists Bird Checklist for Riverbank Centre](resources/Brandon Riverbank Bird Checklist.pdf). Westman Naturalists have produced a bird checklist for Brandon and area, using eBird data and expertise from a number of Westman Naturalists members. This version for Brandon Riverbank Inc highlights birds that are likely to be seen around the Discovery Centre. The checklist can be downloaded here.

## Guidelines

### Guidelines for Field Trip Participants

*Updated:  April 27, 2026*  
[PDF Copy](resources/Westman%20Naturalists%20Inc.%20Guidelines%20for%20Field%20Trip%20Participants.pdf)

#### Guidelines’ Intent
 - Ensure a respectful and comfortable environment for all.
 - Promote consistent, enjoyable, high quality, and safe outings.
 - Have fun exploring and learning about nature together.

#### Guidelines for Field Trip Participants Before and During the Outing

Westman Naturalists Inc. (WN) prepares and advertises events in an email newsletter, on the WN website and social media with a brief description of what the outing entails. Participants may be asked to sign up and provide contact information using a digital link in the posting. The outing leader will provide participants with more detailed information, such as directions, timing, safety information, and other preparatory items via email closer to the date of the outing. 

#### Before signing up for an outing
 - Review the event posting and assess whether you are able to safely participate.
 - Read the waiver you will be expected to sign.

#### Preparing for an outing
 - Review the emailed directions for the event.
 - Be prepared for anticipated weather conditions.
 - Ensure you and your group members pack or wear appropriate footwear, bug spray, sunscreen, clothing and hats.
 - Pack sufficient water and snacks or a lunch for the duration of the event.	
 - Please notify the Trip Leader if you have signed up and cannot attend the outing

#### During an outing
 - Sign the waiver form, and for your children as necessary.
 - Parents or guardians are responsible for supervising their children at all times. 😊
 - Introduce yourself and include brief information about yourself, as you feel comfortable.
 - Watch for common dangers such as poison ivy, tree roots, or other tripping hazards and point them out to other group members.
 - Stay together as a group, for safety and to keep the outing on schedule.
 - Tell one of the leaders if you are feeling unwell or if you have to leave the outing early.
 - Respect the natural environment by practicing Leave No Trace principles: leave only footprints and take only photographs.
 - If you would like to contribute photos to be shared on WN social media, please email them to the WN email – contact@westmannaturalists.ca
 - For events held on private property, participants are requested to respect the owner’s wishes.
 - Permission to access the property is granted for the duration of the outing only and does not extend past the event.
 - Remember to have fun! Questions and comments are welcomed and we encourage you to share your knowledge with other group members! 


### Guidelines for Field Trip Leaders and Co-Leaders

*Updated May 1, 2026*  
[PDF Copy](resources/Westman%20Naturalists%20Inc.%20Guidelines%20for%20Trip%20and%20Co-leaders.pdf)


#### Guidelines’ Intent
 - Ensure a respectful, welcoming and comfortable environment for all.
 - Promote consistent, high quality, and safe outings.
 - Have fun exploring and learning about nature together.
 - To set expectations for conducting Westman Naturalists Inc. (WN) outings.

#### Details for Leaders
 - At least two leaders approved by the outings committee are required for an outing. 
 - At least one leader must be a WN board or committee member.
 - An additional leader or co-leader may be any individual, but is usually an active WN member, or an external expert such as a landowner, local guide, or a subject expert.
 - The WN trip leaders are responsible for administrative tasks for the outing. 
 - Leaders will collaboratively determine the division of leadership responsibilities in the field. 
 - If the outing has more than twelve participants then the leaders should try to recruit another suitable co-leader, or two with over 20 participants.

#### Planning Guidelines for Trip Leaders and Co-Leaders 
 - Coordinate with landowners, or leaders external to WN, to decide on a rough itinerary, meeting place, maximum number of people for the trip, and site-specific information, e.g., parking. 
 - If the outing is on private land, permission is for one time. Landowners’ wishes must be respected. 
 - Inquire if the landowner wishes to serve as a trip leader. Should they decline, it will be necessary to recruit two leaders.
 - Share participant guidelines and this document with landowners and external leaders. 
 - Carefully plan the outing including the intended route, distance, and time estimated for both driving and walking segments.
 - Work with the communications committee to confirm details of the outing for publicity, preferably at least three weeks ahead of the date of the outing and include the following: 
    - Title and Trip Leader names; 
    - Date, time, and location; 
    - Approximate length of outing (both time and distance walked); 
    - List of possible hazards for moving around at the site, (e.g., poison ivy, tree roots, rough terrain); 
    - Reminders about bringing food, water and appropriate clothing and footwear and include a “weather permitting” statement. 
 - WN trip leaders are responsible for ensuring that an email is sent from, or cc’d to, the WN email address to all electronically registered participants, which includes:
    - Additional details of the trip;
    - Directions for driving and parking;
    - Cancellation instructions;
    - Description of possible hazards including weather; 
 - Check the sign-up form to ensure there are enough cars for carpooling. 

#### Planning Guidelines for Trip Leaders and Co-Leaders (cont.)
 - Cancellation - The WN trip leaders, after consultation with co- and external leaders, will determine whether the trip will proceed based on weather conditions or other unforeseen circumstances. Electronically registered participants will be notified of any cancellation via email, phone, or text as soon as possible. For outings that don’t require signing up ahead of time, the leaders must go to the meeting point and discuss the wiseness of cancellation with potential participants. 

#### Guidelines for Trip Leaders and Co-Leaders (day of the outing)
 - Meet at carpooling site and if needed, coordinate carpooling. 
 - Ensure all participants have signed the waiver, respond to any questions. 
 - Remind participants the purpose of the waiver is to enhance safety for everyone, and encourage everyone to look out for each other. 
 - Remind participants that signing the waiver means they are OK with photographs. If anyone is not OK, they must alert the Trip or Co-leader. 
 - If there are children on the outing, remind the parents or guardians they are responsible for their children at all times. 
 - Start with introductions: first names are fine and offer the option of sharing one thing about themselves.
 - Invite participants to share any good photos they take with the WN email. Photos may be posted on social media. 
 - Invite participants to share their knowledge or point out anything interesting to other participants. 
 - Advise all participants that someone will making an eBird list and invite them to share their sightings.
 - Encourage people to stay in one group, or split into multiple groups if there are large numbers. 
 - Respect the environment. Leave only footprints and take only photos.
 - Remind participants to tell the Trip or Co-leader if they feel unwell or plan to leave the outing early. 

#### During the outing
 - Keep track of where people are and be aware of their well-being. 
 - Try to talk with everyone briefly during the event and check to see if everyone is comfortable, paying attention to new(er) participants. 
 - Whenever possible help people out with plant or animal ID, and let the group know about interesting observations.
 - Encourage a friendly atmosphere where everyone is learning and sharing their knowledge as much as possible. 

#### After the outing
 - The WN trip leader takes a photo or scan of the signed and dated portion of the waiver and saves it to the WN Google drive or asks a WN board member to do this.
 - If any field trip participant asks to receive the WN newsletter, email this person’s name and email address to a Communications Committee member. 
 - If an external leader or landowner is involved, the Trip or Co-Leader should contact them to thank them to share gratitude, and provide a brief summary of the outing.  A token of appreciation may be presented, such as a WN calendar.