---
title: "Waiver"
---

Download a [printable copy of our waiver here](resources/WAIVER260708.pdf). A physical copy will be present at most of our outings for participants to sign.

## Waiver and Release

**Note: By signing this document, you will waive certain legal rights. Please read carefully before signing.**

To **Westman Naturalists Inc.**, Brandon, Manitoba

I hereby acknowledge:

1. That I am fully aware of the risks associated with participation in the above-named activity.

2. That I have freely accepted responsibility for accidents to myself arising from hazards and risks which could include, but are not limited to: steep, uneven, slippery or jagged terrain; dangerous insects, plants, and animals; sudden extreme weather conditions; forest deadfalls; tree stumps; holes and depressions below the snow or ground surface; slippery ice; thin ice on frozen creeks, lakes and marshes; cold water; dense bush; poor trails.

3. That I recognize and acknowledge the following are my responsibility: inappropriate clothing; inadequate physical fitness or health; not obeying directions of the hike or activity coordinator; intentionally separating from the group activity; and failure to exercise good judgment or pay due care and attention.

4. That I hereby waive any claim I may have against the owners, renters or caretakers of the land and Westman Naturalists Inc. and any of its directors, executive members or trip leaders and release them from all liability for any damages, loss of income, costs, expenses, or other injury of any kind whatsoever arising out of injuries or damages sustained by me as a result of my participation in this activity.

5. **Photography/ Multimedia Consent:**<br><br>I hereby authorize Westman Naturalists Inc. to use audio, video, or photographs taken during this activity (which may include me and/or my children) for promotion of the Club’s activities. I further allow Westman Naturalists Inc. to share these media with citizen science organizations. No names will be used in association with any images or recordings.<br><br>***If you do not give photo/multimedia consent** please tell the leader of the activity/trip and mark your signature line with "No photos".*

I acknowledge that this waiver and release will be binding upon myself, my family, heirs, executors, administrators, assignee, and successors.

***Field Trip Leaders:*** Please return completed forms to a Westman Naturalists Inc. director.

*Waiver last updated on 8 July, 2026.*